### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [nguyenvanven/coderSchooLab2#1]
Hi @nguyenvanven . 
Could you please check out your homework 2? It seemed like I could not send message to receiver .

**Comment by nguyenvanven** [comment]
I found the problem, do you mean that you cannot add friend?
It's because of my last commit for blocking user function, i forgot to check all function again.
It works now. Thanks

**Comment by coderschoolreview** [comment]
Hi @dpqhuy, nice work with your assignment 2 :+1:

The goals of this homework are:
- to know how to implement authentication from scratch in Rails with the help of the has_secure_password class method and the bcrypt gem (while understanding what they do under the hood)
- to design a more complex schema for a web app and be more familiar with ActiveRecord API such as custom foreign keys for belongs_to/has_many, using has_many :through and building more advanced queries by chaining where, order, and merge
- to build more complex forms in views that involve multiple models.

## Quick review:

I see has_secure_password in your User model and you define current_user. Great job! Correctly handle user signup in Users controller and user login in Sessions controller 
Nicely define belongs_to/has_many with custom class name and `has_many :through` for friendship
Good job on doing Block function 
Nice query-ing non Friended Users

## Area to Improve:

You should put some foreign_key in your relationships. 
You should pay more attention to the UI. It looks simple .
You should put validations in every models, don't wanna let the user put some crazy things in there.

Congrats again on the submission. Everyone has limited time; it's good to see you .... Let us know if you have any feedback.

**Comment by AlecksJohanssen** [comment]
Hi @nguyenvanven, nice work with your assignment 2 :+1:

The goals of this homework are:

* to know how to implement authentication from scratch in Rails with the help of the has_secure_password class method and the bcrypt gem (while understanding what they do under the hood)
* to design a more complex schema for a web app and be more familiar with ActiveRecord API such as custom foreign keys for belongs_to/has_many, using has_many :through and building more advanced queries by chaining where, order, and merge
* to build more complex forms in views that involve multiple models.

## Quick review:

I see has_secure_password in your User model and you define current_user. Great job! Correctly handle user signup in Users controller and user login in Sessions controller 
Nicely define belongs_to/has_many with custom class name and `has_many :through` for friendship
Good job on doing Block function 
Nice query-ing non Friended Users

## Area to Improve:

You should put some foreign_key in your relationships. 
You should pay more attention to the UI. It looks simple .
You should put validations in every models, don't wanna let the user put some crazy things in there.



Congrats again on the submission. Everyone has limited time; it's good to see you .... Let us know if you have any feedback.
